# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 0.3

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: doc/source/conf.py

python:
  version: 3.8

conda:
  environment: .readthedocs_environment.yml
