name: particles
channels:
  - defaults
  - conda-forge
  - JimClark
dependencies:
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - sphinxcontrib-napoleon
  - jupyter
  - jupyter_client
  - ipykernel
  - pylag
