name: pylag
channels:
  - defaults
  - conda-forge
  - geo-down-under
  - JimClark
dependencies:
  - python=3.8
  - pylag
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - sphinxcontrib-napoleon
  - jupyter
  - jupyter_client
  - ipykernel
