{% set name = "PyLag" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

source:
  path: ./
  
requirements:
  host:
    - python
    - pip
    - openmpi
    - mpi4py
    - numpy>=1.18
    - cython>=0.29
  build:
    - {{ compiler('cxx') }}
  run:
    - python
    - mpi4py
    - numpy>=1.18
    - scipy>=1.4.1
    - cython>=0.29
    - progressbar
    - natsort
    - netCDF4
    - cftime>=1.1
    - configparser
    - stripy
    - joblib<=0.17
    - shapely
    - pyproj
    - nose2

test:
  import:
    - pylag.main
    - pylag.parallel.main
  requires:
    - nose2

about:
  home: https://gitlab.ecosystem-modelling.pml.ac.uk/PyLag/PyLag
  license: GPL
  license_family: GPL
  summary: A particle tracking tool for marine applications
